"""Build the lab in an EMPTY Houdini scene, then save a new project file.

Use Windows > Python Source Editor in Houdini, load/paste this file, and Apply.
The script checks every node's geometry before saving the scene.
It does not clear an existing scene or overwrite an existing project file.
"""
from pathlib import Path
import json
import re
import hou

DEFAULT_REPO = Path(r"C:\Users\fujin\Desktop\UPENN\Term3\CIS5660\lab05-stylization")
REPO = Path(__file__).resolve().parents[1] if "__file__" in globals() else DEFAULT_REPO

WHEAT = ["F=FF[-FF]F[-FF]FF-"]
SQUARE = ["F=F+F-F-F+F"]
FERN_PREMISE = 'A(1)'
FERN = [
    "A(l)=F(l)[+(65)B(l*1.4)][-(65)B(l*1.4)]-(1.2)A(l*0.94)",
    "B(l)=F(l*0.32)[+(55)C(l*0.5)][-(55)C(l*0.5)]B(l*0.85)",
    "C(l)={. +(25)f(l*0.55). -(50)f(l*0.55). -(130)f(l*0.55). -(50)f(l*0.55).}",
]


def set_parm(node, name, value):
    parm = node.parm(name)
    if parm is None:
        raise RuntimeError(f"Missing Houdini parameter {node.path()}/{name}")
    parm.set(value)


def make_lsystem(parent, name, premise, rules, angle, generation, position):
    node = parent.createNode("lsystem", name)
    node.setPosition(hou.Vector2(position))
    # Explicitly remove factory rules, including rules on the other Rules tabs.
    for parm in node.parms():
        if re.fullmatch(r"rule\d+", parm.name()):
            parm.set("")
        elif re.fullmatch(r"userule\d+", parm.name()):
            parm.set(0)
    for key, value in {
        "premise": premise,
        "generations": generation,
        "angleinit": angle,
        "stepinit": 1.0,
        "randscale": 0.0,
    }.items():
        set_parm(node, key, value)
    for index, rule in enumerate(rules, 1):
        set_parm(node, f"rule{index}", rule)
        set_parm(node, f"userule{index}", 1)
    # Resolve the menu by its visible label instead of guessing an enum number.
    type_parm = node.parm("type")
    template = type_parm.parmTemplate()
    matches = [i for i, label in enumerate(template.menuLabels())
               if label.strip().lower() == "skeleton"]
    if len(matches) != 1:
        raise RuntimeError(f"Cannot resolve Skeleton menu: {template.menuLabels()}")
    if template.type() == hou.parmTemplateType.Menu:
        type_parm.set(matches[0])
    else:
        type_parm.set(template.menuItems()[matches[0]])
    node.setComment(
        f"Generation {generation}; premise: {premise}; angle: {angle} degrees\n"
        + "\n".join(rules)
        + "\nFor the two puzzles, capture the Rules tab with this node selected."
    )
    node.setGenericFlag(hou.nodeFlag.DisplayComment, False)
    geometry = node.geometry()
    if node.errors():
        raise RuntimeError(f"{node.path()}: {node.errors()}")
    if not geometry or not geometry.points():
        raise RuntimeError(f"No geometry generated by {node.path()}")
    return node, {
        "node": node.path(), "generation": generation,
        "points": len(geometry.points()), "primitives": len(geometry.prims()),
        "warnings": list(node.warnings()),
    }


def build():
    obj = hou.node("/obj")
    if obj.children():
        raise RuntimeError("Please run this script in a NEW EMPTY scene. Existing objects were left untouched.")
    geo = obj.createNode("geo", "lab05_grammars")
    geo.setComment("Three exercises. Display one L-system at a time using its blue flag.")
    configs = [
        ("wheat", "F", WHEAT, 20, (1, 2, 3)),
        ("square", "+(90)F", SQUARE, 90, (1, 2, 3)),
        ("fern", FERN_PREMISE, FERN, 25, (4, 8, 14)),
    ]
    reports, nodes = [], []
    for row, (name, premise, rules, angle, generations) in enumerate(configs):
        for col, generation in enumerate(generations):
            node, report = make_lsystem(
                geo, f"{name}_n{generation:02}", premise, rules,
                angle, generation, (col * 4, -row * 2),
            )
            node.setColor(hou.Color((0.34, 0.58, 0.39) if name == "fern" else (0.58, 0.64, 0.73)))
            nodes.append(node)
            reports.append(report)
            if name == "fern":
                color = geo.createNode("color", f"{node.name()}_color")
                color.setInput(0, node)
                color.parmTuple("color").set((0.18, 0.48, 0.24))
                color.setPosition(node.position() + hou.Vector2((0, -1)))
                color.setComment("Presentation color only; the L-system defines all geometry.")
                nodes.append(color)
    for node in nodes:
        node.setDisplayFlag(False)
        node.setRenderFlag(False)
    final = nodes[-1]
    final.setDisplayFlag(True)
    final.setRenderFlag(True)
    geo.node("fern_n14").setSelected(True, clear_all_selected=True)
    if hou.isUIAvailable():
        viewer = hou.ui.paneTabOfType(hou.paneTabType.SceneViewer)
        if viewer:
            viewer.setPwd(geo)
            viewer.curViewport().changeType(hou.geometryViewportType.Front)
            viewer.curViewport().frameAll()
        network = hou.ui.paneTabOfType(hou.paneTabType.NetworkEditor)
        if network:
            network.setPwd(geo)
            network.homeToSelection()
    category = str(hou.licenseCategory()).lower()
    extension = ".hiplc" if "indie" in category else ".hipnc" if any(x in category for x in ("apprentice", "noncommercial", "education")) else ".hip"
    folder = REPO / "houdini"
    folder.mkdir(exist_ok=True)
    filename = folder / ("lab05_grammars" + extension)
    version = 2
    while filename.exists():
        filename = folder / (f"lab05_grammars_v{version:03}" + extension)
        version += 1
    hou.hipFile.save(str(filename))
    report_file = filename.with_suffix(".validation.json")
    report_file.write_text(json.dumps({
        "houdini_version": hou.applicationVersionString(),
        "project": hou.hipFile.path(),
        "nodes": reports,
        "note": "Successful geometry cooks. Visual comparison and screenshots are separate steps.",
    }, indent=2), encoding="utf-8")
    print(f"Saved project: {hou.hipFile.path()}")
    print("Select a node, enable its blue display flag, and use Front view to inspect it.")
    print("Capture actual Houdini rule screenshots before treating the README as submission-ready.")


if __name__ == "__main__":
    build()
